### ISSUE TITLE
Please Update To 3.0.0ALPHA12

### ISSUE THREAD

**Issue by joshuasing** [ShatteredAtom/CustomSetting#1]
Please Update To 3.0.0ALPHA12 so i can get this awesome plugin!

**Comment by XuPaperCup** [comment]
Just update

**Comment by XuPaperCup** [comment]
You can download in:https://poggit.pmmp.io/r/31245/CustomSetting_pr-1.phar

**Comment by ShatteredAtom** [comment]
i updated the api to the latest and it is pending review

**Comment by joshuasing** [comment]
Thanks!
