### ISSUE TITLE
New Line & Links

### ISSUE THREAD

**Issue by joshuasing** [ShatteredAtom/CustomSetting#5]
Hi! @ShatteredAtom
how do you make a new line?
and can you please add links to websites?
and can i put my server logo at the top of the page?
Thank You.

**Comment by ShatteredAtom** [comment]
to make a new line it uses the pmmp formatting so try these formats
\n
{line}
im very sorry but it's not possible to add clickable links in mcpe
i will experiment with the image embed at the top of the page
