### ISSUE TITLE
How to:

### ISSUE THREAD

**Issue by Wertzui123** [ShatteredAtom/CustomSetting#8]
Add Buttons wich are executing commands

Add text fields where you can write in something and when you close the settings a command will be executed

Thanks for an answer.

**Comment by ShatteredAtom** [comment]
This isnt so much a command execution plugin as it is a quality of life settings decoration plugin 
make suggestions that are relevant to the current use for the plugin and they will be considered. Cheers!

**Comment by Wertzui123** [comment]
Oh, ok sorry
