### ISSUE TITLE
How Can This Not Work Pls Help

### ISSUE THREAD

**Issue by Napoleon-x** [ShatteredAtom/CustomSetting#9]
{
  "type": "custom_form",
  "title": "Herobrinic Regions",
  "icon": {
    "type": "url",
    "data": "https://img.icons8.com/color/96/000000/crafting-table.png"
  },
  "content": [
    {
      "type": "label",
      "text": "Hello user, Wellcome to our Newly Made Server Called The Herobrinic Regions.Here we respect our members and play fun games while making friends on the way.We have Games Such as Skyblock,Factions and much more! Be aware any funny bussiness,we have staff watching you and we will be a lookout for new staff members so who knows maybe if you sign up we might consider you as staff. "
    }
  ]
}

**Comment by mkevinam** [comment]
{
  "type": "custom_form",
  "title": "§4§lRed§fFire",
  "icon": {
    "type": "url",
    "data": "https://img.icons8.com/color/96/000000/crafting-table.png"
  },
  "content": [
    {
      "type": "label",
      "text": "Hello user, Wellcome to our Newly Made Server Called The Herobrinic Regions.Here we respect our members and play fun games while making friends on the way.We have Games Such as Skyblock,Factions and much more! Be aware any funny bussiness,we have staff watching you and we will be a lookout for new staff members so who knows maybe if you sign up we might consider you as staff."
    }
  ]
}

**Comment by mkevinam** [comment]
try that
